apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lokistack-simple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JoaoBraveCoding/multicluster-logging
    targetRevision: 667f5b17b859e9a47e170b98f995c82d6feac4c5
    path: chart/charts/lokistack
    helm:
      values: |
        spec:
          managementState: Unmanaged
          size: 1x.extra-small # Different from MCOA
          storage:
            schemas:
            - effectiveDate: "2025-01-01" # Different from MCOA
              version: v13
            secret:
              name: test # Different from MCOA
              type: s3
          storageClassName: gp3-csi
          tenants:
            authorization:
              opa:
                url: ""
              roleBindings:
              - name: cluster-reader
                roles:
                - cluster-reader
                subjects:
                - kind: group
                  name: mcoa-logs-admin
              roles:
              - name: cluster-reader
                permissions:
                - write # Different from MCOA
                resources:
                - logs
                tenants: []
            mode: static
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-cluster-management-observability
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
