apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: default-stack-instance-global
  namespace: open-cluster-management-observability
spec:
  managementState: Unmanaged
  size: 1x.extra-small # Different from MCOA
  storage:
    schemas:
    - effectiveDate: "2025-01-01" # Different from MCOA
      version: v13
    secret:
      name: test # Different from MCOA
      type: s3
  storageClassName: gp3-csi
  tenants:
    authorization:
      opa:
        url: ""
      roleBindings:
      - name: cluster-reader
        roles:
        - cluster-reader
        subjects:
        - kind: group
          name: mcoa-logs-admin
      roles:
      - name: cluster-reader
        permissions:
        - write # Different from MCOA
        resources:
        - logs
        tenants: []
    mode: static